name: pass_king
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependency_overrides:
  intl: ^0.18.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_messaging:
  firebase_storage:
  flutter_bloc: ^8.1.3
  awesome_dialog: ^3.1.0
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  dio: ^5.3.0
  equatable: ^2.0.5
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  intl: ^0.18.0
  logger: ^2.0.1
  path_provider: ^2.0.15
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.12
  toastification: ^0.0.3
  progress_indicators: ^1.0.0
  pin_code_fields: ^8.0.1

  flutter_rating_bar: ^4.0.1
  font_awesome_flutter:

  flutter_credit_card: ^3.0.7
  flutter_dotenv: ^5.1.0
  flutter_stripe: ^9.3.0
  expansion_tile_card: ^3.0.0
  syncfusion_flutter_sliders:
  expandable: ^5.0.1
  dotted_border:
  sizer:
  intl_phone_field:
  dropdown_search:
  google_maps_flutter:

  curved_navigation_bar:
  flutter_image_slideshow:
  multiselect_formfield: ^0.1.7
  multi_dropdown: ^2.1.0
  calendar_appbar: ^0.0.6
  image_picker:
  geocoding:
  easy_stepper:
  loading_animation_widget: ^1.2.0+4
  flag:
  page_transition:
  html: ^0.15.4
  permission_handler: ^11.0.0
  my_fatoorah: ^3.3.0
  jwt_decoder: ^2.0.1
  google_fonts:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
    - assets/.env

  fonts:
    - family: Taga
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
    - family: montserrat
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300