// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC23Z8w530JaT7b2kWgF-SV0PnqE80UK94',
    appId: '1:803771038668:web:3722a077edf07ac29d3b69',
    messagingSenderId: '803771038668',
    projectId: 'qrcity-363116',
    authDomain: 'qrcity-363116.firebaseapp.com',
    storageBucket: 'qrcity-363116.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGnJzhVwUywvSsFls_jpQ1AQoA5x9fmL0',
    appId: '1:803771038668:android:2af6cc414ed11ed69d3b69',
    messagingSenderId: '803771038668',
    projectId: 'qrcity-363116',
    storageBucket: 'qrcity-363116.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc8Q2UvZOyegaW2ZrTveslOLsVJTxoj4I',
    appId: '1:803771038668:ios:9a3fb06b12d7b09c9d3b69',
    messagingSenderId: '803771038668',
    projectId: 'qrcity-363116',
    storageBucket: 'qrcity-363116.appspot.com',
    androidClientId: '803771038668-c7gs4dgdcsf54mccre2l6adin487qjc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.representative',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc8Q2UvZOyegaW2ZrTveslOLsVJTxoj4I',
    appId: '1:803771038668:ios:e7bdcab13fab8a7f9d3b69',
    messagingSenderId: '803771038668',
    projectId: 'qrcity-363116',
    storageBucket: 'qrcity-363116.appspot.com',
    androidClientId: '803771038668-c7gs4dgdcsf54mccre2l6adin487qjc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.representative.RunnerTests',
  );
}
