// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMqBr5mR0J94I_3IZIDNNCzZ-ZS0EMn3Y',
    appId: '1:843462803695:web:3b2c0f18af2cac2d425b1a',
    messagingSenderId: '843462803695',
    projectId: 'king-e8575',
    authDomain: 'king-e8575.firebaseapp.com',
    storageBucket: 'king-e8575.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5QEQJGDkN9o8S5HDbC8huMp4tNTAo2lg',
    appId: '1:843462803695:android:5eab39a321a0829e425b1a',
    messagingSenderId: '843462803695',
    projectId: 'king-e8575',
    storageBucket: 'king-e8575.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_xdH35q2kt06yh3XqILwATQ7NostJDs4',
    appId: '1:843462803695:ios:8267224f976248bf425b1a',
    messagingSenderId: '843462803695',
    projectId: 'king-e8575',
    storageBucket: 'king-e8575.firebasestorage.app',
    iosBundleId: 'com.example.passKing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_xdH35q2kt06yh3XqILwATQ7NostJDs4',
    appId: '1:843462803695:ios:8267224f976248bf425b1a',
    messagingSenderId: '843462803695',
    projectId: 'king-e8575',
    storageBucket: 'king-e8575.firebasestorage.app',
    iosBundleId: 'com.example.passKing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMqBr5mR0J94I_3IZIDNNCzZ-ZS0EMn3Y',
    appId: '1:843462803695:web:7a393889cae9f4d6425b1a',
    messagingSenderId: '843462803695',
    projectId: 'king-e8575',
    authDomain: 'king-e8575.firebaseapp.com',
    storageBucket: 'king-e8575.firebasestorage.app',
  );
}
